In [1]:
from distarray.apps import dacluster

In [2]:
dacluster.start(24, "--engines=PBSEngineSetLauncher")

2015-11-10 21:29:42.741 [IPClusterStart] Starting ipcluster with [daemon=False]
2015-11-10 21:29:42.745 [IPClusterStart] Creating pid file: /home/zonca/.ipython/profile_default/pid/ipcluster.pid
2015-11-10 21:29:42.749 [IPClusterStart] Starting Controller with LocalControllerLauncher
2015-11-10 21:29:43.752 [IPClusterStart] Starting 24 Engines with PBSEngineSetLauncher
2015-11-10 21:29:44.805 [IPClusterStart] Job submitted with job id: u'1259819'
2015-11-10 21:31:14.806 [IPClusterStart] Engines appear to have started successfully


In [24]:
# some utility imports
from __future__ import print_function
from pprint import pprint
from matplotlib import pyplot as plt

# main imports
import numpy as np
import distarray.globalapi as da

# reduce precision on printed array values
np.set_printoptions(precision=2)

# display figures inline
%matplotlib inline

In [20]:
# a 4-row 5-column NumPy array with random contents
nparr = np.random.rand(24, 5)
nparr

array([[ 0.87,  0.01,  0.72,  0.93,  0.87],
       [ 0.02,  0.29,  0.55,  0.37,  0.25],
       [ 0.37,  0.31,  0.54,  0.12,  0.2 ],
       [ 0.53,  0.9 ,  0.15,  0.44,  0.46],
       [ 0.67,  0.52,  0.21,  0.61,  0.14],
       [ 0.64,  0.26,  0.25,  0.02,  0.1 ],
       [ 0.61,  0.88,  0.23,  0.48,  0.05],
       [ 0.98,  0.87,  0.38,  0.56,  0.76],
       [ 0.4 ,  0.45,  0.33,  0.8 ,  0.86],
       [ 0.07,  0.25,  0.73,  0.35,  0.92],
       [ 0.34,  0.39,  0.1 ,  0.87,  0.23],
       [ 0.46,  0.75,  0.83,  0.32,  0.17],
       [ 0.06,  0.86,  0.5 ,  0.5 ,  0.78],
       [ 0.19,  0.76,  0.63,  0.42,  0.88],
       [ 0.21,  0.06,  0.03,  0.13,  0.37],
       [ 0.49,  0.46,  0.62,  0.8 ,  0.59],
       [ 0.55,  0.57,  0.67,  0.73,  0.05],
       [ 0.61,  0.9 ,  0.12,  0.86,  0.91],
       [ 0.24,  0.19,  0.54,  0.83,  0.93],
       [ 0.68,  0.92,  0.37,  0.67,  0.59],
       [ 0.48,  0.82,  0.51,  0.51,  0.17],
       [ 0.87,  0.61,  0.16,  0.86,  0.65],
       [ 0.69,  0.57,  0.89,  0.

In [21]:
from distarray.globalapi import Context
context = Context()

In [22]:
# Make a DistArray from a NumPy array.
# This will push sections of the original NumPy array out
# to the engines.
darr = context.fromarray(nparr)
darr

<DistArray(shape=(24, 5), targets=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])>

In [23]:
# Print the array section stored on each engine
for i, a in enumerate(darr.get_localarrays()):
    print(i, a)

0 [[ 0.87  0.01  0.72  0.93  0.87]]
1 [[ 0.02  0.29  0.55  0.37  0.25]]
2 [[ 0.37  0.31  0.54  0.12  0.2 ]]
3 [[ 0.53  0.9   0.15  0.44  0.46]]
4 [[ 0.67  0.52  0.21  0.61  0.14]]
5 [[ 0.64  0.26  0.25  0.02  0.1 ]]
6 [[ 0.61  0.88  0.23  0.48  0.05]]
7 [[ 0.98  0.87  0.38  0.56  0.76]]
8 [[ 0.4   0.45  0.33  0.8   0.86]]
9 [[ 0.07  0.25  0.73  0.35  0.92]]
10 [[ 0.34  0.39  0.1   0.87  0.23]]
11 [[ 0.46  0.75  0.83  0.32  0.17]]
12 [[ 0.06  0.86  0.5   0.5   0.78]]
13 [[ 0.19  0.76  0.63  0.42  0.88]]
14 [[ 0.21  0.06  0.03  0.13  0.37]]
15 [[ 0.49  0.46  0.62  0.8   0.59]]
16 [[ 0.55  0.57  0.67  0.73  0.05]]
17 [[ 0.61  0.9   0.12  0.86  0.91]]
18 [[ 0.24  0.19  0.54  0.83  0.93]]
19 [[ 0.68  0.92  0.37  0.67  0.59]]
20 [[ 0.48  0.82  0.51  0.51  0.17]]
21 [[ 0.87  0.61  0.16  0.86  0.65]]
22 [[ 0.69  0.57  0.89  0.78  0.77]]
23 [[ 0.14  0.38  0.74  0.29  0.43]]


# Distributed array functions

In [25]:
# NumPy provides `ufuncs`, or Universal Functions, that operate
# elementwise over NumPy arrays.
np.sin(nparr)

array([[ 0.76,  0.01,  0.66,  0.8 ,  0.77],
       [ 0.02,  0.29,  0.53,  0.36,  0.24],
       [ 0.36,  0.3 ,  0.51,  0.12,  0.2 ],
       [ 0.5 ,  0.78,  0.15,  0.43,  0.44],
       [ 0.62,  0.5 ,  0.21,  0.57,  0.14],
       [ 0.59,  0.26,  0.25,  0.02,  0.1 ],
       [ 0.57,  0.77,  0.23,  0.46,  0.05],
       [ 0.83,  0.77,  0.37,  0.53,  0.69],
       [ 0.39,  0.44,  0.32,  0.72,  0.76],
       [ 0.07,  0.25,  0.67,  0.35,  0.8 ],
       [ 0.34,  0.38,  0.1 ,  0.76,  0.23],
       [ 0.44,  0.68,  0.74,  0.31,  0.17],
       [ 0.06,  0.76,  0.48,  0.48,  0.7 ],
       [ 0.19,  0.69,  0.59,  0.41,  0.77],
       [ 0.21,  0.06,  0.03,  0.13,  0.36],
       [ 0.47,  0.44,  0.58,  0.72,  0.55],
       [ 0.52,  0.54,  0.62,  0.67,  0.05],
       [ 0.57,  0.78,  0.12,  0.76,  0.79],
       [ 0.24,  0.19,  0.51,  0.74,  0.8 ],
       [ 0.63,  0.79,  0.36,  0.62,  0.56],
       [ 0.46,  0.73,  0.49,  0.49,  0.17],
       [ 0.77,  0.57,  0.16,  0.76,  0.61],
       [ 0.64,  0.54,  0.78,  0.

In [26]:
# DistArray provides ufuncs as well, for `DistArray`s.
import distarray.globalapi as da
da.sin(darr)

<DistArray(shape=(24, 5), targets=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])>

In [27]:
# `toarray` makes a NumPy array out of a DistArray, pulling all of the
# pieces back to the client.  We do this to display the contents of the
# DistArray.
da.sin(darr).toarray()

array([[ 0.76,  0.01,  0.66,  0.8 ,  0.77],
       [ 0.02,  0.29,  0.53,  0.36,  0.24],
       [ 0.36,  0.3 ,  0.51,  0.12,  0.2 ],
       [ 0.5 ,  0.78,  0.15,  0.43,  0.44],
       [ 0.62,  0.5 ,  0.21,  0.57,  0.14],
       [ 0.59,  0.26,  0.25,  0.02,  0.1 ],
       [ 0.57,  0.77,  0.23,  0.46,  0.05],
       [ 0.83,  0.77,  0.37,  0.53,  0.69],
       [ 0.39,  0.44,  0.32,  0.72,  0.76],
       [ 0.07,  0.25,  0.67,  0.35,  0.8 ],
       [ 0.34,  0.38,  0.1 ,  0.76,  0.23],
       [ 0.44,  0.68,  0.74,  0.31,  0.17],
       [ 0.06,  0.76,  0.48,  0.48,  0.7 ],
       [ 0.19,  0.69,  0.59,  0.41,  0.77],
       [ 0.21,  0.06,  0.03,  0.13,  0.36],
       [ 0.47,  0.44,  0.58,  0.72,  0.55],
       [ 0.52,  0.54,  0.62,  0.67,  0.05],
       [ 0.57,  0.78,  0.12,  0.76,  0.79],
       [ 0.24,  0.19,  0.51,  0.74,  0.8 ],
       [ 0.63,  0.79,  0.36,  0.62,  0.56],
       [ 0.46,  0.73,  0.49,  0.49,  0.17],
       [ 0.77,  0.57,  0.16,  0.76,  0.61],
       [ 0.64,  0.54,  0.78,  0.

In [28]:
# A NumPy binary ufunc.
nparr + nparr

array([[ 1.74,  0.01,  1.45,  1.85,  1.74],
       [ 0.04,  0.59,  1.11,  0.75,  0.49],
       [ 0.74,  0.62,  1.08,  0.23,  0.39],
       [ 1.05,  1.8 ,  0.31,  0.88,  0.92],
       [ 1.33,  1.04,  0.42,  1.22,  0.29],
       [ 1.27,  0.52,  0.51,  0.04,  0.19],
       [ 1.22,  1.75,  0.46,  0.95,  0.1 ],
       [ 1.95,  1.74,  0.76,  1.11,  1.53],
       [ 0.79,  0.91,  0.65,  1.6 ,  1.72],
       [ 0.14,  0.51,  1.47,  0.71,  1.84],
       [ 0.68,  0.79,  0.2 ,  1.74,  0.46],
       [ 0.91,  1.49,  1.66,  0.63,  0.34],
       [ 0.13,  1.72,  1.  ,  1.  ,  1.56],
       [ 0.37,  1.53,  1.25,  0.84,  1.76],
       [ 0.43,  0.11,  0.05,  0.26,  0.75],
       [ 0.97,  0.91,  1.24,  1.6 ,  1.18],
       [ 1.1 ,  1.13,  1.34,  1.47,  0.09],
       [ 1.22,  1.79,  0.24,  1.72,  1.82],
       [ 0.48,  0.39,  1.08,  1.67,  1.87],
       [ 1.36,  1.83,  0.73,  1.35,  1.19],
       [ 0.96,  1.64,  1.01,  1.03,  0.34],
       [ 1.74,  1.22,  0.32,  1.71,  1.31],
       [ 1.39,  1.14,  1.78,  1.

In [29]:
# The equivalent DistArray ufunc.
# Notice that a new DistArray is created without
# pulling data back to the client.
darr + darr

<DistArray(shape=(24, 5), targets=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])>

In [30]:
# Contents of the resulting DistArray.
(darr + darr).toarray()

array([[ 1.74,  0.01,  1.45,  1.85,  1.74],
       [ 0.04,  0.59,  1.11,  0.75,  0.49],
       [ 0.74,  0.62,  1.08,  0.23,  0.39],
       [ 1.05,  1.8 ,  0.31,  0.88,  0.92],
       [ 1.33,  1.04,  0.42,  1.22,  0.29],
       [ 1.27,  0.52,  0.51,  0.04,  0.19],
       [ 1.22,  1.75,  0.46,  0.95,  0.1 ],
       [ 1.95,  1.74,  0.76,  1.11,  1.53],
       [ 0.79,  0.91,  0.65,  1.6 ,  1.72],
       [ 0.14,  0.51,  1.47,  0.71,  1.84],
       [ 0.68,  0.79,  0.2 ,  1.74,  0.46],
       [ 0.91,  1.49,  1.66,  0.63,  0.34],
       [ 0.13,  1.72,  1.  ,  1.  ,  1.56],
       [ 0.37,  1.53,  1.25,  0.84,  1.76],
       [ 0.43,  0.11,  0.05,  0.26,  0.75],
       [ 0.97,  0.91,  1.24,  1.6 ,  1.18],
       [ 1.1 ,  1.13,  1.34,  1.47,  0.09],
       [ 1.22,  1.79,  0.24,  1.72,  1.82],
       [ 0.48,  0.39,  1.08,  1.67,  1.87],
       [ 1.36,  1.83,  0.73,  1.35,  1.19],
       [ 0.96,  1.64,  1.01,  1.03,  0.34],
       [ 1.74,  1.22,  0.32,  1.71,  1.31],
       [ 1.39,  1.14,  1.78,  1.

# Reductions

In [31]:
# NumPy sum
print("sum:", nparr.sum())
print("sum over an axis:", nparr.sum(axis=1))

sum: 60.3359638765
sum over an axis: [ 3.4   1.49  1.53  2.48  2.15  1.27  2.24  3.55  2.84  2.33  1.94  2.52
  2.7   2.88  0.8   2.95  2.57  3.4   2.74  3.23  2.49  3.15  3.71  1.98]


In [32]:
# DistArray sum
print("sum:", darr.sum(), darr.sum().toarray())
print("sum over an axis:", darr.sum(axis=1), darr.sum(axis=1).toarray())

sum: <DistArray(shape=(), targets=[0])> 60.3359638765
sum over an axis: <DistArray(shape=(24,), targets=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])> [ 3.4   1.49  1.53  2.48  2.15  1.27  2.24  3.55  2.84  2.33  1.94  2.52
  2.7   2.88  0.8   2.95  2.57  3.4   2.74  3.23  2.49  3.15  3.71  1.98]


# Indexing and Slicing

In [34]:
# Our example array, as a reminder:
darr.toarray()

array([[ 0.87,  0.01,  0.72,  0.93,  0.87],
       [ 0.02,  0.29,  0.55,  0.37,  0.25],
       [ 0.37,  0.31,  0.54,  0.12,  0.2 ],
       [ 0.53,  0.9 ,  0.15,  0.44,  0.46],
       [ 0.67,  0.52,  0.21,  0.61,  0.14],
       [ 0.64,  0.26,  0.25,  0.02,  0.1 ],
       [ 0.61,  0.88,  0.23,  0.48,  0.05],
       [ 0.98,  0.87,  0.38,  0.56,  0.76],
       [ 0.4 ,  0.45,  0.33,  0.8 ,  0.86],
       [ 0.07,  0.25,  0.73,  0.35,  0.92],
       [ 0.34,  0.39,  0.1 ,  0.87,  0.23],
       [ 0.46,  0.75,  0.83,  0.32,  0.17],
       [ 0.06,  0.86,  0.5 ,  0.5 ,  0.78],
       [ 0.19,  0.76,  0.63,  0.42,  0.88],
       [ 0.21,  0.06,  0.03,  0.13,  0.37],
       [ 0.49,  0.46,  0.62,  0.8 ,  0.59],
       [ 0.55,  0.57,  0.67,  0.73,  0.05],
       [ 0.61,  0.9 ,  0.12,  0.86,  0.91],
       [ 0.24,  0.19,  0.54,  0.83,  0.93],
       [ 0.68,  0.92,  0.37,  0.67,  0.59],
       [ 0.48,  0.82,  0.51,  0.51,  0.17],
       [ 0.87,  0.61,  0.16,  0.86,  0.65],
       [ 0.69,  0.57,  0.89,  0.

In [35]:
# The shapes of the local sections of our DistArray
darr.localshapes()

[(1, 5),
 (1, 5),
 (1, 5),
 (1, 5),
 (1, 5),
 (1, 5),
 (1, 5),
 (1, 5),
 (1, 5),
 (1, 5),
 (1, 5),
 (1, 5),
 (1, 5),
 (1, 5),
 (1, 5),
 (1, 5),
 (1, 5),
 (1, 5),
 (1, 5),
 (1, 5),
 (1, 5),
 (1, 5),
 (1, 5),
 (1, 5)]

In [36]:
# Return the value of a single element
darr[0, 2]

0.72489182795044593

In [37]:
# Take a column slice
darr_view = darr[:, 3]  # all rows, third column
print(darr_view)
print(darr_view.toarray())

<DistArray(shape=(24,), targets=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])>
[ 0.93  0.37  0.12  0.44  0.61  0.02  0.48  0.56  0.8   0.35  0.87  0.32
  0.5   0.42  0.13  0.8   0.73  0.86  0.83  0.67  0.51  0.86  0.78  0.29]


In [38]:
# Slices return a new DistArray that is a view on the
# original, just like in NumPy.
# Changes in the view change the original array.
darr_view[3] = -0.99
print("view:")
print(darr_view.toarray())

print("original:")
print(darr.toarray())

view:
[ 0.93  0.37  0.12 -0.99  0.61  0.02  0.48  0.56  0.8   0.35  0.87  0.32
  0.5   0.42  0.13  0.8   0.73  0.86  0.83  0.67  0.51  0.86  0.78  0.29]
original:
[[ 0.87  0.01  0.72  0.93  0.87]
 [ 0.02  0.29  0.55  0.37  0.25]
 [ 0.37  0.31  0.54  0.12  0.2 ]
 [ 0.53  0.9   0.15 -0.99  0.46]
 [ 0.67  0.52  0.21  0.61  0.14]
 [ 0.64  0.26  0.25  0.02  0.1 ]
 [ 0.61  0.88  0.23  0.48  0.05]
 [ 0.98  0.87  0.38  0.56  0.76]
 [ 0.4   0.45  0.33  0.8   0.86]
 [ 0.07  0.25  0.73  0.35  0.92]
 [ 0.34  0.39  0.1   0.87  0.23]
 [ 0.46  0.75  0.83  0.32  0.17]
 [ 0.06  0.86  0.5   0.5   0.78]
 [ 0.19  0.76  0.63  0.42  0.88]
 [ 0.21  0.06  0.03  0.13  0.37]
 [ 0.49  0.46  0.62  0.8   0.59]
 [ 0.55  0.57  0.67  0.73  0.05]
 [ 0.61  0.9   0.12  0.86  0.91]
 [ 0.24  0.19  0.54  0.83  0.93]
 [ 0.68  0.92  0.37  0.67  0.59]
 [ 0.48  0.82  0.51  0.51  0.17]
 [ 0.87  0.61  0.16  0.86  0.65]
 [ 0.69  0.57  0.89  0.78  0.77]
 [ 0.14  0.38  0.74  0.29  0.43]]


# Apply a function locally on the engines

In [44]:
def get_local_random():
    import numpy
    return numpy.random.randint(10)

context.apply(get_local_random)

[0, 0, 3, 1, 2, 5, 3, 3, 3, 8, 1, 6, 8, 5, 0, 2, 9, 3, 0, 3, 4, 5, 9, 2]

In [47]:
def get_local_var(darr):
    """Another local computation."""
    return darr.ndarray.var()

context.apply(get_local_var, args=(darr.key,))

[0.11755605095088388,
 0.030054420890902666,
 0.021387824159555407,
 0.41595727885845263,
 0.045465583701768196,
 0.045421066055898865,
 0.083444625785817392,
 0.046641638164434424,
 0.048537693617781034,
 0.098297078461812598,
 0.068134387401419721,
 0.06298898608651278,
 0.078211423006549291,
 0.061310813490726902,
 0.01550877075877195,
 0.014699152827412281,
 0.059271872176695495,
 0.090602610143151407,
 0.090289769783438584,
 0.031082741899277677,
 0.042367547027462239,
 0.066371268417878299,
 0.011504584078104079,
 0.039948378423662161]

# Register a function

In [51]:
def local_demean(la):
    """Return the local array with the mean removed."""
    return la.ndarray - la.ndarray.mean()
context.register(local_demean)

In [53]:
context.local_demean(darr)

[array([[ 0.19, -0.67,  0.04,  0.25,  0.19]]),
 array([[-0.28, -0.  ,  0.26,  0.08, -0.05]]),
 array([[ 0.07,  0.  ,  0.23, -0.19, -0.11]]),
 array([[ 0.32,  0.69, -0.06, -1.2 ,  0.25]]),
 array([[ 0.24,  0.09, -0.22,  0.18, -0.29]]),
 array([[ 0.38,  0.01,  0.  , -0.24, -0.16]]),
 array([[ 0.16,  0.43, -0.22,  0.03, -0.4 ]]),
 array([[ 0.27,  0.16, -0.33, -0.15,  0.05]]),
 array([[-0.17, -0.11, -0.24,  0.23,  0.29]]),
 array([[-0.4 , -0.21,  0.27, -0.11,  0.45]]),
 array([[-0.04,  0.01, -0.29,  0.48, -0.16]]),
 array([[-0.05,  0.24,  0.33, -0.19, -0.34]]),
 array([[-0.48,  0.32, -0.04, -0.04,  0.24]]),
 array([[-0.39,  0.19,  0.05, -0.16,  0.31]]),
 array([[ 0.05, -0.1 , -0.13, -0.03,  0.21]]),
 array([[-0.1 , -0.13,  0.03,  0.21, -0.  ]]),
 array([[ 0.04,  0.05,  0.16,  0.22, -0.47]]),
 array([[-0.07,  0.22, -0.56,  0.18,  0.23]]),
 array([[-0.31, -0.36, -0.01,  0.29,  0.39]]),
 array([[ 0.03,  0.27, -0.28,  0.03, -0.05]]),
 array([[-0.02,  0.32,  0.01,  0.02, -0.33]]),
 array([[ 0.2